env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  complexity: ['error', 10]
  no-undef: off
  no-underscore-dangle: off
  no-use-before-define: off
  no-unused-vars: off
  import/extensions: off
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  "@typescript-eslint/no-use-before-define": ["error"]
  "@typescript-eslint/no-unused-vars": "error"
  react/prop-types: off
  react/jsx-filename-extension:
    - error
    - extensions: [".tsx"]
  prettier/prettier:
    - error
settings:
  "import/resolver": "webpack"
